import Head from 'next/head'
import {BsFillMoonStarsFill, bsfILLmOONsTARSfILL} from 'react-icons/bs'
import {AiFillLinkedin, AiFillGithub} from 'react-icons/ai'
import Image from 'next/image';
import selfie from '../public/me.png'
import useState from 'react';

export default function Home() {
  return (
    <div>
      <head>
        <title>Kevin Smith Portfolios</title>
        <meta name="description" content='Generated by create NS React App' />
        <link rel="icon" href="./public/favicon.ico" />
      </head>
      
      <main classname="bg-white px-10 md-px-20 lg:px-40">

        <section className='min-h-screen'>
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">Lore Ipsum</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill  className="cursor-pointer text-2xl"/>
              </li>
              <li>
                <a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">Resume</a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
            Kevin Smith</h2>
            <h3 className="text-2lx py-2">Developer and Engineer</h3>
            <p className="text-md py-5 leading-8 text-gray-800">
              I am a developer and engineer with a passion for learning and building. 
              I have a background in Software engineering and have worked in the FinTech industry for the past 5 years. 
            </p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <a href='https://github.com/kevinsmith115' target='blank'>
              <AiFillGithub /> 
            </a>
            <a href='https://www.linkedin.com/in/kevindaresmith/' target='blank'>
              <AiFillLinkedin />
            </a>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden">
            <Image src={selfie} layout="fill" objectFit='Cover'  />
          </div>
        </section>
        
        <section>
          <div>
            <h3 className='text-3xl py-1'>Services I offer</h3>
            <p className='text-md py-5 leading-8 text-gray-800'>
            Since the beginning of my career, I have been passionate about creating software that is easy to use,
            </p>
          </div>
        
        </section>
        

      </main>
    </div>
  )
}
